---
- Hypervisor:
      - Router:
            icon: si-proxmox
            description: Proxmox
            href: "{{HOMEPAGE_VAR_router_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_router_ip}}"
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_router_ip}}"
                username: "{{HOMEPAGE_VAR_cluster_api_username}}"
                password: "{{HOMEPAGE_VAR_cluster_api_password}}"
                node: router
      - Server:
            icon: si-proxmox
            description: Proxmox
            href: "{{HOMEPAGE_VAR_server_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_server_ip}}"
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_server_ip}}"
                username: "{{HOMEPAGE_VAR_cluster_api_username}}"
                password: "{{HOMEPAGE_VAR_cluster_api_password}}"
                node: server
      - Worker:
            icon: si-proxmox
            description: Proxmox
            href: "{{HOMEPAGE_VAR_worker_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_worker_ip}}"
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_worker_ip}}"
                username: "{{HOMEPAGE_VAR_cluster_api_username}}"
                password: "{{HOMEPAGE_VAR_cluster_api_password}}"
                node: worker
      - 🔒 Router:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_router_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_router_url}}"
      - 🔒 Server:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_server_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_server_url}}"
      - 🔒 Worker:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_worker_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_worker_url}}"
- Fritz & DNS & Nginx:
      - FritzBox:
            icon: https://avm.de/typo3conf/ext/avm/Resources/Public/Images/logo.svg
            href: "{{HOMEPAGE_VAR_fritzbox_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_fritzbox_ip}}"
            widget:
                type: fritzbox
                url: "{{HOMEPAGE_VAR_fritzbox_ip}}"
                fields:
                    [
                        "connectionStatus",
                        "received",
                        "sent",
                        "externalIPAddress",
                    ]
      - Pi-hole:
            icon: si-pihole
            href: "{{HOMEPAGE_VAR_pihole_ip}}/admin"
            siteMonitor: "{{HOMEPAGE_VAR_pihole_ip}}/admin"
            widget:
                type: pihole
                url: "{{HOMEPAGE_VAR_pihole_ip}}"
                key: "{{HOMEPAGE_VAR_pihole_key}}"
      - Speedtest:
            icon: si-speedtest
            href: "{{HOMEPAGE_VAR_speedtest_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_speedtest_ip}}"
            widget:
                type: speedtest
                url: "{{HOMEPAGE_VAR_speedtest_ip}}"
      - Nginx Proxy Manager:
            icon: si-nginx
            href: "{{HOMEPAGE_VAR_nginx_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_nginx_ip}}"
            widget:
                type: npm
                url: "{{HOMEPAGE_VAR_nginx_ip}}"
                username: "{{HOMEPAGE_VAR_username}}"
                password: "{{HOMEPAGE_VAR_password}}"
      - 🔒 FritzBox:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_fritzbox_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_fritzbox_url}}"
      - 🔒 Pi-hole:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_pihole_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_pihole_url}}"
      - 🔒 Speedtest:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_speedtest_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_speedtest_url}}"
      - 🔒 Nginx Proxy Manager:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_nginx_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_nginx_url}}"
- Stuff:
      - HomePage:
            icon: si-homeassistantcommunitystore
            description: Your HomePage
            href: "{{HOMEPAGE_VAR_homepage_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_homepage_ip}}"
      - Bitwarden:
            icon: si-bitwarden
            description: Your Bitwarden
            href: "{{HOMEPAGE_VAR_bitwarden_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_bitwarden_ip}}"
      - Mealie:
            icon: si-franprix
            description: Your Mealie
            href: "{{HOMEPAGE_VAR_mealie_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_mealie_ip}}"
      - Spotify:
            icon: si-spotify
            description: Your Spotify
            href: "{{HOMEPAGE_VAR_spotify_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_spotify_ip}}"
      - 🔒 HomePage:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_homepage_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_homepage_url}}"
      - 🔒 Bitwarden:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_bitwarden_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_bitwarden_url}}"
      - 🔒 Mealie:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_mealie_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_mealie_url}}"
      - 🔒 Spotify:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_spotify_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_spotify_url}}"
- Minecraft:
      - Ptero Panel:
            icon: si-pterodactyl
            href: "{{HOMEPAGE_VAR_ptero_panel_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_panel_ip}}"
      - Ptero Wing 1:
            icon: si-pterodactyl
            href: "{{HOMEPAGE_VAR_ptero_wings_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_wings_ip}}"
      - Minecraft Server:
            icon: si-minecraft
            href: "{{HOMEPAGE_VAR_minecraft_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_minecraft_ip}}"
      - 🔒 Ptero Panel:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_ptero_panel_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_panel_url}}"
      - 🔒 Ptero Wing 1:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_ptero_wings_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_wings_url}}"
      - 🔒 Minecraft Server:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_minecraft_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_minecraft_url}}"
