---
- Machines:
      - Router:
            icon: si-proxmox
            description: Proxmox
            href: "{{HOMEPAGE_VAR_router_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_router_ip}}"
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_router_ip}}"
                username: "{{HOMEPAGE_VAR_cluster_api_username}}"
                password: "{{HOMEPAGE_VAR_cluster_api_password}}"
                node: router
      - Server:
            icon: si-proxmox
            description: Proxmox
            href: "{{HOMEPAGE_VAR_server_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_server_ip}}"
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_server_ip}}"
                username: "{{HOMEPAGE_VAR_cluster_api_username}}"
                password: "{{HOMEPAGE_VAR_cluster_api_password}}"
                node: server
      - 🔒 Router:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_router_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_router_url}}"
      - 🔒 Server:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_server_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_server_url}}"
- Networking:
      - FritzBox:
            icon: si-1dot1dot1dot1
            href: "{{HOMEPAGE_VAR_fritzbox_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_fritzbox_ip}}"
            widget:
                type: fritzbox
                url: "{{HOMEPAGE_VAR_fritzbox_ip}}"
                fields:
                    [
                        "connectionStatus",
                        "received",
                        "sent",
                        "externalIPAddress",
                    ]
      - Pi-hole:
            icon: si-pihole
            href: "{{HOMEPAGE_VAR_pihole_ip}}/admin"
            siteMonitor: "{{HOMEPAGE_VAR_pihole_ip}}/admin"
            widget:
                type: pihole
                url: "{{HOMEPAGE_VAR_pihole_ip}}"
                key: "{{HOMEPAGE_VAR_pihole_key}}"
      - Speedtest:
            icon: si-speedtest
            href: "{{HOMEPAGE_VAR_speedtest_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_speedtest_ip}}"
            widget:
                type: speedtest
                url: "{{HOMEPAGE_VAR_speedtest_ip}}"
      - Nginx Proxy Manager:
            icon: si-nginx
            href: "{{HOMEPAGE_VAR_nginx_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_nginx_ip}}"
            widget:
                type: npm
                url: "{{HOMEPAGE_VAR_nginx_ip}}"
                username: "{{HOMEPAGE_VAR_username}}"
                password: "{{HOMEPAGE_VAR_password}}"
      - 🔒 FritzBox:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_fritzbox_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_fritzbox_url}}"
      - 🔒 Pi-hole:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_pihole_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_pihole_url}}"
      - 🔒 Speedtest:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_speedtest_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_speedtest_url}}"
      - 🔒 Nginx Proxy Manager:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_nginx_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_nginx_url}}"
- Files & Pictures:
      - TrueNas:
            icon: si-truenas
            href: "{{HOMEPAGE_VAR_nas_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_nas_ip}}"
      - Pairdrop:
            icon: si-dropbox
            href: "{{HOMEPAGE_VAR_pairdrop_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_pairdrop_ip}}"
      - Paperless:
            icon: si-paperlessngx
            href: "{{HOMEPAGE_VAR_paper_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_paper_ip}}"
      - 🔒 TrueNas:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_nas_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_nas_url}}"
      - 🔒 Pairdrop:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_pairdrop_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_pairdrop_url}}"
      - 🔒 Paperless:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_paper_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_paper_url}}"
- Stuff:
      - HomePage:
            icon: si-homepage
            href: "{{HOMEPAGE_VAR_homepage_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_homepage_ip}}"
      - Spotify:
            icon: si-spotify
            href: "{{HOMEPAGE_VAR_spotify_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_spotify_ip}}"
      - 🔒 HomePage:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_homepage_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_homepage_url}}"
      - 🔒 Spotify:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_spotify_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_spotify_url}}"
- Minecraft Admin:
      - Ptero Panel:
            icon: si-pterodactyl
            href: "{{HOMEPAGE_VAR_ptero_panel_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_panel_ip}}"
      - Ptero Wing 1 (FORGE):
            icon: si-pterodactyl
            href: "{{HOMEPAGE_VAR_ptero_wingsone_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_wingsone_ip}}"
      - Ptero Wing 2 (VANILLA):
            icon: si-pterodactyl
            href: "{{HOMEPAGE_VAR_ptero_wingstwo_ip}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_wingstwo_ip}}"
      - 🔒 Ptero Panel:
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_ptero_panel_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_panel_url}}"
      - 🔒 Ptero Wing 1 (FORGE):
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_ptero_wingsone_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_wingsone_url}}"
      - 🔒 Ptero Wing 2 (VANILLA):
            icon: si-inertia
            href: "{{HOMEPAGE_VAR_ptero_wingstwo_url}}"
            siteMonitor: "{{HOMEPAGE_VAR_ptero_wingstwo_url}}"
- Minecraft Servers:
      - Server Forge:
            icon: si-minecraft
            href: "{{HOMEPAGE_VAR_minecraftone_url}}"
            description: "{{HOMEPAGE_VAR_minecraftone_ip}} / {{HOMEPAGE_VAR_minecraftone_url}}"
      - Server Vanilla:
            icon: si-minecraft
            href: "{{HOMEPAGE_VAR_minecrafttwo_url}}"
            description: "{{HOMEPAGE_VAR_minecrafttwo_ip}} / {{HOMEPAGE_VAR_minecrafttwo_url}}"
