---
- resources:
      cpu: true
      memory: true
      disk: /

- search:
      provider: "{{HOMEPAGE_VAR_search_provider}}"
      target: _blank

- datetime:
      text_size: xl
      format:
          timeStyle: short
