version: "3.8"
services:
    speedtest:
        restart: unless-stopped
        container_name: openspeedtest
        ports:
            - "80:3000"
            - "443:3001"
        image: openspeedtest/latest
        environment:
            PUID: $PUID
            PGID: $PGID
            DISABLE_IPV6: $DISABLE_IPV6
        env_file: .env
