services:
    server:
        image: "yooooomi/your_spotify_server:latest"
        container_name: your_spotify_server
        env_file: .env
        restart: unless-stopped
        ports:
            - 8088:8080
        environment:
            API_ENDPOINT: $API_ENDPOINT
            CLIENT_ENDPOINT: $CLIENT_ENDPOINT
            DISABLE_IPV6: $DISABLE_IPV6
            SPOTIFY_PUBLIC: $SPOTIFY_PUBLIC
            SPOTIFY_SECRET: $SPOTIFY_SECRET
            TIMEZONE: Europe/Berlin
            CORS: $CORS
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        container_name: mongo
        restart: unless-stopped
        image: mongo:6
        volumes:
            - ./your_spotify_db:/data/db

    web:
        image: "yooooomi/your_spotify_client:latest"
        container_name: your_spotify_client
        env_file: .env
        restart: unless-stopped
        ports:
            - 3003:3000
        environment:
            API_ENDPOINT: $API_ENDPOINT
