version: "3.8"
services:
    mealie:
        image: ghcr.io/mealie-recipes/mealie:latest
        container_name: mealie
        ports:
            - "9925:9000"
        deploy:
            resources:
                limits:
                    memory: 500M
        depends_on:
            - postgres
        volumes:
            - mealie-data:/app/data/
        environment:
            PUID: $PUID
            PGID: $PGID
            DISABLE_IPV6: $DISABLE_IPV6
            TZ: Germany/Berlin
            MAX_WORKERS: 1
            WEB_CONCURRENCY: 1
            BASE_URL: $BASE_URL
            DB_ENGINE: postgres
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_SERVER: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: mealie
        restart: unless-stopped
        env_file: .env
    postgres:
        image: postgres:15
        container_name: postgres
        volumes:
            - ./mealie-pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        restart: unless-stopped
        env_file: .env
volumes:
    mealie-data:
        driver: local
    mealie-pgdata:
        driver: local
