services:
    firefly_iii_core:
        image: fireflyiii/core:latest
        hostname: firefly_iii_core
        container_name: firefly_iii_core
        restart: unless-stopped
        volumes:
            - firefly_iii_upload:/var/www/html/storage/upload
        env_file: .env
        networks:
            - firefly_iii
        ports:
            - 3001:8080
        depends_on:
            - db
    db:
        image: mariadb:lts
        hostname: db
        container_name: firefly_iii_db
        restart: unless-stopped
        env_file: .db.env
        networks:
            - firefly_iii
        volumes:
            - firefly_iii_db:/var/lib/mysql
    cron:
        image: alpine
        restart: unless-stopped
        container_name: firefly_iii_cron
        env_file: .env
        command: sh -c "
            apk add tzdata
            && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
            | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$STATIC_CRON_TOKEN;echo\"
            | crontab -
            && crond -f -L /dev/stdout"
        networks:
            - firefly_iii

volumes:
    firefly_iii_upload:
    firefly_iii_db:

networks:
    firefly_iii:
        driver: bridge
