services:
    database:
        container_name: database
        image: mariadb:10.11
        env_file: .env
        restart: unless-stopped
        ports:
            - $PORT_DB:3306
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db:/var/lib/mysql
            - dbetc:/etc/mysql
        networks:
            - panel
        environment:
            MYSQL_PASSWORD: $MYSQL_PASS
            MYSQL_ROOT_PASSWORD: $MYSQL_PASS_ROOT
            MYSQL_DATABASE: "panel"
            MYSQL_USER: "pterodactyl"

    cache:
        container_name: cache
        image: redis:alpine3.18
        env_file: .env
        networks:
            - panel
        restart: unless-stopped
        volumes:
            - cache:/data

    panel:
        container_name: panel
        hostname: pterodactyl_panel
        image: ghcr.io/pterodactyl/panel:v1.11.10
        env_file: .env
        restart: unless-stopped
        networks:
            - panel
        ports:
            - $PORT_HTTP:80
        links:
            - database
            - cache
        volumes:
            - env:/app/var
        environment:
            MAIL_FROM: $MAIL_FROM
            MAIL_DRIVER: "smtp"
            MAIL_HOST: $MAIL_SERVER
            MAIL_PORT: $MAIL_PORT
            MAIL_USERNAME: $MAIL_USERNAME
            MAIL_PASSWORD: $MAIL_PASS
            MAIL_ENCRYPTION: "true"
            APP_URL: $PTERO_PANEL_URL
            APP_TIMEZONE: Europe/Berlin
            APP_SERVICE_AUTHOR: $MAIL_FROM
            TRUSTED_PROXIES: $TRUSTED_PROXIES
            DB_PASSWORD: $MYSQL_PASS
            APP_ENV: "production"
            APP_ENVIRONMENT_ONLY: "false"
            CACHE_DRIVER: "redis"
            SESSION_DRIVER: "redis"
            QUEUE_DRIVER: "redis"
            REDIS_HOST: "cache"
            DB_HOST: "database"
            DB_PORT: $PORT_DB
networks:
    panel:

volumes:
    cache:
    db:
    env:
    dbetc:
