##### GENERATED START #####
# Order: defaults_values, image, container_name, depends_on, environment, ports, volumes, healthcheck
x-defaults: &defaults_values
    restart: unless-stopped # Automatically restart the container unless manually stopped.
    env_file: .env # Load additional environment variables from a .env file.
    environment:
        TZ: Europe/Berlin # Set the application timezone.
        PUID: ${PUID} # Set the user ID for file permissions using an environment variable.
        PGID: ${PGID} # Set the group ID for file permissions using an environment variable.
        DISABLE_IPV6: ${DISABLE_IPV6} # Optionally disable IPv6 support using an environment variable.
    logging: # Configure log rotation to prevent excessive disk usage.
        driver: local # Use the default local logging driver.
        options:
            max-size: "20m" # Limit individual log file size to 20MB.
            max-file: "5" # Keep a maximum of 5 log files.
            compress: "true" # Compress log files to save disk space.

services:
    # Watchtower service to automatically update containers when new versions of their images are available.
    watchtower:
        <<: *defaults_values
        image: containrrr/watchtower # The official Watchtower image.
        container_name: watchtower # Name the container "watchtower" for easier identification.
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw # Mount the Docker socket to allow Watchtower to interact with the Docker daemon.
        command:
            --cleanup --interval 86400 # Configure Watchtower:
            # --cleanup: Remove old images after updates.
            # --interval 86400: Check for updates every 24 hours (86400 seconds).
    ##### GENERATED END #####

    ##### SERVICES START ##### ADD YOUR SERVICES BELOW #####
    netalertx:
        <<: *defaults_values
        image: jokobsk/netalertx:latest
        container_name: NetAlertX
        privileged: true
        security_opt:
            - no-new-privileges:true
        environment:
            PORT: 3000
        volumes:
            - ./netalertx/db:/app/db:rw
            - ./netalertx/config:/app/config:rw
            - ./netalertx/logs:/app/front/log:rw
        network_mode: host
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
