services:
    # Watchtower service to automatically update containers when new versions of their images are available.
    watchtower:
        image: containrrr/watchtower # The official Watchtower image.
        container_name: watchtower # Name the container "watchtower" for easier identification.
        restart: unless-stopped # Automatically restart Watchtower unless manually stopped.
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket to allow Watchtower to interact with the Docker daemon.
        command:
            --cleanup --interval 86400 # Configure Watchtower:
            # --cleanup: Remove old images after updates.
            # --interval 86400: Check for updates every 24 hours (86400 seconds).
        networks:
            - custom_network # Attach Watchtower to the same custom network as other services.

    duckdns:
        image: lscr.io/linuxserver/duckdns:latest
        container_name: duckdns
        restart: unless-stopped # Automatically restart the container unless manually stopped.
        env_file:
            - .env # Load additional environment variables from a .env file.
        environment:
            - PUID=${PUID} # Set the user ID for file permissions using an environment variable.
            - PGID=${PGID} # Set the group ID for file permissions using an environment variable.
            - TZ=Europe/Berlin
            - SUBDOMAINS=${DUCKDNS_DOMAINS}
            - TOKEN=${DUCKDNS_TOKEN}
            - UPDATE_IP=ipv4
        volumes:
            - ./duckdns-updater:/config:rw
        networks:
            - custom_network # Attach the container to the custom network.

# Define the custom bridge network for communication between services.
networks:
    custom_network:
        driver: bridge # Use the bridge network driver for service communication.
