services:
    # Watchtower service to automatically update containers when new versions of their images are available.
    watchtower:
        image: containrrr/watchtower # The official Watchtower image.
        container_name: watchtower # Name the container "watchtower" for easier identification.
        restart: unless-stopped # Automatically restart Watchtower unless manually stopped.
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket to allow Watchtower to interact with the Docker daemon.
        command:
            --cleanup --interval 86400 # Configure Watchtower:
            # --cleanup: Remove old images after updates.
            # --interval 86400: Check for updates every 24 hours (86400 seconds).
        networks:
            - custom_network # Attach Watchtower to the same custom network as other services.

    # Nginx Proxy Manager service to manage reverse proxy configurations.
    nginx-proxy-manager:
        image: jc21/nginx-proxy-manager:latest # Use the latest version of the Nginx Proxy Manager image for updates.
        container_name: nginx # Name the container "nginx" for identification.
        hostname: nginx # Set the hostname for the container.
        restart: unless-stopped # Automatically restart the container unless manually stopped.
        ports:
            - "80:80" # Map port 80 on the host to port 80 in the container (HTTP).
            - "81:81" # Map port 81 on the host to port 81 in the container (Admin panel).
            - "443:443" # Map port 443 on the host to port 443 in the container (HTTPS).
        environment:
            PUID: ${PUID} # Set the user ID for file permissions using an environment variable.
            PGID: ${PGID} # Set the group ID for file permissions using an environment variable.
            DISABLE_IPV6: ${DISABLE_IPV6} # Optionally disable IPv6 support using an environment variable.
        env_file:
            - .env # Load additional environment variables from a .env file.
        volumes:
            - ./data:/data:rw # Persist container data to the local "data" directory (read-write access).
            - ./letsencrypt:/etc/letsencrypt:rw # Persist Let's Encrypt SSL certificates to the local "letsencrypt" directory (read-write access).
        healthcheck: # Define a health check to monitor container health.
            test: ["CMD", "curl", "-f", "http://localhost:81"] # Use curl to check the admin panel's availability.
            interval: 30s # Perform the health check every 30 seconds.
            timeout: 10s # Wait up to 10 seconds for a response before marking the check as failed.
            retries: 3 # Retry the health check 3 times before marking the container as unhealthy.
            start_period: 10s # Wait 10 seconds after starting the container before running health checks.
        logging: # Configure log rotation to prevent excessive disk usage.
            driver: json-file # Use the default JSON file logging driver.
            options:
                max-size: "10m" # Limit individual log file size to 10MB.
                max-file: "3" # Keep a maximum of 3 log files.
        deploy:
            resources: # Set resource limits to manage the container's impact on the host system.
                limits:
                    cpus: "1" # Limit the container to using 1 CPU core.
                    memory: "768M" # Limit the container to using 768MB of RAM.
        networks:
            - custom_network # Attach the container to the custom network.

    duckdns:
        image: lscr.io/linuxserver/duckdns:latest
        container_name: duckdns
        restart: unless-stopped # Automatically restart the container unless manually stopped.
        env_file:
            - .env # Load additional environment variables from a .env file.
        environment:
            - PUID=${PUID} # Set the user ID for file permissions using an environment variable.
            - PGID=${PGID} # Set the group ID for file permissions using an environment variable.
            - TZ=Europe/Berlin
            - SUBDOMAINS=${DUCKDNS_DOMAINS}
            - TOKEN=${DUCKDNS_TOKEN}
            - UPDATE_IP=ipv4
        volumes:
            - ./duckdns-updater:/config #optional

        networks:
            - custom_network # Attach the container to the custom network.

# Define the custom bridge network for communication between services.
networks:
    custom_network:
        driver: bridge # Use the bridge network driver for service communication.
