services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        env_file: .env
        ports:
            - 3003:443
        environment:
            - PUID=$PUID
            - PGID=$PGID
            - DISABLE_IPV6=$DISABLE_IPV6
            - APP_KEY=$APP_KEY
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=0 */2 * * *
            - PRUNE_RESULTS_OLDER_THAN=90
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
        volumes:
            - ./data:/config
