services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker
        env_file: .env
        ports:
            - 3000:80
            - 3003:443
        environment:
            - PUID=$PUID
            - PGID=$PGID
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=$POSTGRES_NAME
            - DB_USERNAME=$POSTGRES_USER
            - DB_PASSWORD=$POSTGRES_PASSWORD
            - APP_KEY=$APP_KEY
            - SPEEDTEST_SCHEDULE=0 */2 * * *
            - PRUNE_RESULTS_OLDER_THAN=30
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
        volumes:
            - /path/to/data:/config
            - /path/to/directory/web:/etc/ssl/web
        restart: unless-stopped
        depends_on:
            - db

    db:
        image: postgres:15
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_DB=$POSTGRES_NAME
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        volumes:
            - speedtest-db:/var/lib/postgresql/data
volumes:
    speedtest-db:
