version: "3.8"
services:
    server:
        image: "yooooomi/your_spotify_server:latest"
        restart: unless-stopped
        ports:
            - "8088:8080"
        links:
            - mongo
        depends_on:
            - mongo
        env_file: .env
        environment:
            API_ENDPOINT: $API_ENDPOINT
            CLIENT_ENDPOINT: $CLIENT_ENDPOINT
            DISABLE_IPV6: $DISABLE_IPV6
            SPOTIFY_PUBLIC: $SPOTIFY_PUBLIC
            SPOTIFY_SECRET: $SPOTIFY_SECRET
            CORS: $CORS

    mongo:
        container_name: mongo
        restart: unless-stopped
        image: mongo:6
        volumes:
            - ./your_spotify_db:/data/db

    web:
        image: "yooooomi/your_spotify_client:latest"
        restart: unless-stopped
        ports:
            - "3003:3000"
        env_file: .env
        environment:
            API_ENDPOINT: $API_ENDPOINT
