services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db_data:/var/lib/mysql:rw
        networks:
            - app_network

    wordpress:
        image: wordpress:latest
        container_name: wordpress
        depends_on:
            - db
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        volumes:
            - ./wordpress_data:/var/www/html:rw
        networks:
            - app_network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        depends_on:
            - db
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - app_network

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WATCHTOWER_CLEANUP: "true"
            WATCHTOWER_LABEL_ENABLE: "true"
        networks:
            - app_network

networks:
    app_network:
